### PR TITLE
First version

### PR DESCRIPTION
**Pull request by lucilapastore**
Preview of the New York Times website with all the corrections made by the first reviewer included.

### CODE REVIEW

**Comment by ebukaume** [comment]
Hi @lucilapastore :wave: 

Nice job so far, but there are a few things we need to fix.

Firstly, according to the [curriculum](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/), **this project is supposed to be collaborative. May I ask why you did it solo?**

Secondly, you commit and PR messages are not descriptive. You are almost there, but you can do more. You can refer to [this repo](https://github.com/RomuloOliveira/commit-messages-guide) for more on the topic.

Thirdly, stickler did not run on this repo. If you have setup stickler correctly, make sure to turn it ON for this repo. You can refer to [this guide](https://github.com/microverseinc/linters-config/tree/master/css#troubleshooting) to help you with the troubleshooting.

Finally, let's make these changes as listed below:

- [x] The project has a descriptive README.md. (You can refer to [this](https://github.com/othneildrew/Best-README-Template) for a clue on the kind of information to include.)

**Navigation Bar**
- [x] The NY Times logo is a link.

**Footer**
- [x] It should have a fixed position (it sticks to the bottom part of the screen).

**Bottom part**
- [x] It contains links to other articles with image previews.

The last, but not the least; fix the horizontal scroll.

**Kindly submit another code review request after making those changes**

Happy Coding :v: 
**Ebuka Umeokonkwo**
[Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Twitter](https://twitter.com/ebukaume)

**Comment by lucilapastore** [comment]
Hello I did it alone because I didn't have a partner at the time. Can you tell me how to fix the horizontal scroll please? And can you tell me how to fix the stickler errors? because they are thousands and I don't understand them @ebukaume 
Thanks!
Lucila

**Comment by ebukaume** [comment]
> Hello I did it alone because I didn't have a partner at the time. Can you tell me how to fix the horizontal scroll please? And can you tell me how to fix the stickler errors? because they are thousands and I don't understand them @ebukaume
> Thanks!
> Lucila

I am sorry for replying so late; I have been busy. Let's chat on slack, please. My handle is `@echelon `

**Review by whiz25 — CHANGES_REQUESTED** [review]
## Wow your clone looks awesome! :+1: 
You have implemented all the suggested changes by the previous reviewer. That's good.
However, we need to fix one crucial feature.
- [ ] the ```theory of inflation``` section should not be a screenshot. implement that using HTML, CSS and the images found on the original site.

### Please make that change and re-submit for another review.

**Comment by lucilapastore** [comment]
Version with all the corrections included.

**Review by wathigo — APPROVED** [review]
## Hi @lucilapastore  :wave:  
Great work on the project! 
**This is approved**
_Good luck :)_

**Pull request merged**
